// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files/chatResMsg.proto

package com.sy599.game.msg.serverPacket;

public final class ChatResMsg {
  private ChatResMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 code = 1;
    /**
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     */
    int getCode();

    // optional int64 userId = 2;
    /**
     * <code>optional int64 userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int64 userId = 2;</code>
     */
    long getUserId();

    // required string c = 3;
    /**
     * <code>required string c = 3;</code>
     */
    boolean hasC();
    /**
     * <code>required string c = 3;</code>
     */
    java.lang.String getC();
    /**
     * <code>required string c = 3;</code>
     */
    com.google.protobuf.ByteString
        getCBytes();

    // optional string ip = 4;
    /**
     * <code>optional string ip = 4;</code>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 4;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    // optional string userName = 5;
    /**
     * <code>optional string userName = 5;</code>
     */
    boolean hasUserName();
    /**
     * <code>optional string userName = 5;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string userName = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // optional int32 vip = 6;
    /**
     * <code>optional int32 vip = 6;</code>
     */
    boolean hasVip();
    /**
     * <code>optional int32 vip = 6;</code>
     */
    int getVip();

    // optional string s = 7;
    /**
     * <code>optional string s = 7;</code>
     *
     * <pre>
     *性别
     * </pre>
     */
    boolean hasS();
    /**
     * <code>optional string s = 7;</code>
     *
     * <pre>
     *性别
     * </pre>
     */
    java.lang.String getS();
    /**
     * <code>optional string s = 7;</code>
     *
     * <pre>
     *性别
     * </pre>
     */
    com.google.protobuf.ByteString
        getSBytes();

    // optional int64 talkId = 8;
    /**
     * <code>optional int64 talkId = 8;</code>
     */
    boolean hasTalkId();
    /**
     * <code>optional int64 talkId = 8;</code>
     */
    long getTalkId();

    // optional string talkName = 9;
    /**
     * <code>optional string talkName = 9;</code>
     */
    boolean hasTalkName();
    /**
     * <code>optional string talkName = 9;</code>
     */
    java.lang.String getTalkName();
    /**
     * <code>optional string talkName = 9;</code>
     */
    com.google.protobuf.ByteString
        getTalkNameBytes();

    // optional int32 hongbao = 10;
    /**
     * <code>optional int32 hongbao = 10;</code>
     */
    boolean hasHongbao();
    /**
     * <code>optional int32 hongbao = 10;</code>
     */
    int getHongbao();

    // optional int32 hongbaoId = 11;
    /**
     * <code>optional int32 hongbaoId = 11;</code>
     */
    boolean hasHongbaoId();
    /**
     * <code>optional int32 hongbaoId = 11;</code>
     */
    int getHongbaoId();

    // optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;
    /**
     * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
     */
    boolean hasTeam();
    /**
     * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
     */
    com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes getTeam();
    /**
     * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
     */
    com.sy599.game.msg.serverPacket.ChatResMsg.TeamResOrBuilder getTeamOrBuilder();

    // optional int32 systemtype = 13;
    /**
     * <code>optional int32 systemtype = 13;</code>
     */
    boolean hasSystemtype();
    /**
     * <code>optional int32 systemtype = 13;</code>
     */
    int getSystemtype();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.ChatRes}
   *
   * <pre>
   *聊天
   * </pre>
   */
  public static final class ChatRes extends
      com.google.protobuf.GeneratedMessage
      implements ChatResOrBuilder {
    // Use ChatRes.newBuilder() to construct.
    private ChatRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatRes defaultInstance;
    public static ChatRes getDefaultInstance() {
      return defaultInstance;
    }

    public ChatRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              c_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              ip_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              userName_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              vip_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              s_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              talkId_ = input.readInt64();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              talkName_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              hongbao_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              hongbaoId_ = input.readInt32();
              break;
            }
            case 98: {
              com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.Builder subBuilder = null;
              if (((bitField0_ & 0x00000800) == 0x00000800)) {
                subBuilder = team_.toBuilder();
              }
              team_ = input.readMessage(com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(team_);
                team_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000800;
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              systemtype_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_ChatRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_ChatRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes.class, com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatRes> PARSER =
        new com.google.protobuf.AbstractParser<ChatRes>() {
      public ChatRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    // optional int64 userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>optional int64 userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // required string c = 3;
    public static final int C_FIELD_NUMBER = 3;
    private java.lang.Object c_;
    /**
     * <code>required string c = 3;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string c = 3;</code>
     */
    public java.lang.String getC() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string c = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCBytes() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ip = 4;
    public static final int IP_FIELD_NUMBER = 4;
    private java.lang.Object ip_;
    /**
     * <code>optional string ip = 4;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string ip = 4;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string userName = 5;
    public static final int USERNAME_FIELD_NUMBER = 5;
    private java.lang.Object userName_;
    /**
     * <code>optional string userName = 5;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string userName = 5;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 vip = 6;
    public static final int VIP_FIELD_NUMBER = 6;
    private int vip_;
    /**
     * <code>optional int32 vip = 6;</code>
     */
    public boolean hasVip() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 vip = 6;</code>
     */
    public int getVip() {
      return vip_;
    }

    // optional string s = 7;
    public static final int S_FIELD_NUMBER = 7;
    private java.lang.Object s_;
    /**
     * <code>optional string s = 7;</code>
     *
     * <pre>
     *性别
     * </pre>
     */
    public boolean hasS() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string s = 7;</code>
     *
     * <pre>
     *性别
     * </pre>
     */
    public java.lang.String getS() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s = 7;</code>
     *
     * <pre>
     *性别
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = s_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 talkId = 8;
    public static final int TALKID_FIELD_NUMBER = 8;
    private long talkId_;
    /**
     * <code>optional int64 talkId = 8;</code>
     */
    public boolean hasTalkId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 talkId = 8;</code>
     */
    public long getTalkId() {
      return talkId_;
    }

    // optional string talkName = 9;
    public static final int TALKNAME_FIELD_NUMBER = 9;
    private java.lang.Object talkName_;
    /**
     * <code>optional string talkName = 9;</code>
     */
    public boolean hasTalkName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string talkName = 9;</code>
     */
    public java.lang.String getTalkName() {
      java.lang.Object ref = talkName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          talkName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string talkName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTalkNameBytes() {
      java.lang.Object ref = talkName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        talkName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 hongbao = 10;
    public static final int HONGBAO_FIELD_NUMBER = 10;
    private int hongbao_;
    /**
     * <code>optional int32 hongbao = 10;</code>
     */
    public boolean hasHongbao() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 hongbao = 10;</code>
     */
    public int getHongbao() {
      return hongbao_;
    }

    // optional int32 hongbaoId = 11;
    public static final int HONGBAOID_FIELD_NUMBER = 11;
    private int hongbaoId_;
    /**
     * <code>optional int32 hongbaoId = 11;</code>
     */
    public boolean hasHongbaoId() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 hongbaoId = 11;</code>
     */
    public int getHongbaoId() {
      return hongbaoId_;
    }

    // optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;
    public static final int TEAM_FIELD_NUMBER = 12;
    private com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes team_;
    /**
     * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
     */
    public boolean hasTeam() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
     */
    public com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes getTeam() {
      return team_;
    }
    /**
     * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
     */
    public com.sy599.game.msg.serverPacket.ChatResMsg.TeamResOrBuilder getTeamOrBuilder() {
      return team_;
    }

    // optional int32 systemtype = 13;
    public static final int SYSTEMTYPE_FIELD_NUMBER = 13;
    private int systemtype_;
    /**
     * <code>optional int32 systemtype = 13;</code>
     */
    public boolean hasSystemtype() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 systemtype = 13;</code>
     */
    public int getSystemtype() {
      return systemtype_;
    }

    private void initFields() {
      code_ = 0;
      userId_ = 0L;
      c_ = "";
      ip_ = "";
      userName_ = "";
      vip_ = 0;
      s_ = "";
      talkId_ = 0L;
      talkName_ = "";
      hongbao_ = 0;
      hongbaoId_ = 0;
      team_ = com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.getDefaultInstance();
      systemtype_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasTeam()) {
        if (!getTeam().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, vip_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, talkId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getTalkNameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, hongbao_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, hongbaoId_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeMessage(12, team_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, systemtype_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, vip_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, talkId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getTalkNameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, hongbao_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, hongbaoId_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, team_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, systemtype_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.ChatRes}
     *
     * <pre>
     *聊天
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ChatResMsg.ChatResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_ChatRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_ChatRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes.class, com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTeamFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        c_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        vip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        s_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        talkId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        talkName_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        hongbao_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        hongbaoId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        if (teamBuilder_ == null) {
          team_ = com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.getDefaultInstance();
        } else {
          teamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        systemtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_ChatRes_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes build() {
        com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes buildPartial() {
        com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes result = new com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.c_ = c_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.vip_ = vip_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.s_ = s_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.talkId_ = talkId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.talkName_ = talkName_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.hongbao_ = hongbao_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.hongbaoId_ = hongbaoId_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        if (teamBuilder_ == null) {
          result.team_ = team_;
        } else {
          result.team_ = teamBuilder_.build();
        }
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.systemtype_ = systemtype_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes other) {
        if (other == com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasC()) {
          bitField0_ |= 0x00000004;
          c_ = other.c_;
          onChanged();
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000008;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000010;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasVip()) {
          setVip(other.getVip());
        }
        if (other.hasS()) {
          bitField0_ |= 0x00000040;
          s_ = other.s_;
          onChanged();
        }
        if (other.hasTalkId()) {
          setTalkId(other.getTalkId());
        }
        if (other.hasTalkName()) {
          bitField0_ |= 0x00000100;
          talkName_ = other.talkName_;
          onChanged();
        }
        if (other.hasHongbao()) {
          setHongbao(other.getHongbao());
        }
        if (other.hasHongbaoId()) {
          setHongbaoId(other.getHongbaoId());
        }
        if (other.hasTeam()) {
          mergeTeam(other.getTeam());
        }
        if (other.hasSystemtype()) {
          setSystemtype(other.getSystemtype());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        if (!hasC()) {
          
          return false;
        }
        if (hasTeam()) {
          if (!getTeam().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ChatResMsg.ChatRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 code = 1;
      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // optional int64 userId = 2;
      private long userId_ ;
      /**
       * <code>optional int64 userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 userId = 2;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 2;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // required string c = 3;
      private java.lang.Object c_ = "";
      /**
       * <code>required string c = 3;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string c = 3;</code>
       */
      public java.lang.String getC() {
        java.lang.Object ref = c_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string c = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCBytes() {
        java.lang.Object ref = c_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string c = 3;</code>
       */
      public Builder setC(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string c = 3;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000004);
        c_ = getDefaultInstance().getC();
        onChanged();
        return this;
      }
      /**
       * <code>required string c = 3;</code>
       */
      public Builder setCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c_ = value;
        onChanged();
        return this;
      }

      // optional string ip = 4;
      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 4;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ip_ = value;
        onChanged();
        return this;
      }

      // optional string userName = 5;
      private java.lang.Object userName_ = "";
      /**
       * <code>optional string userName = 5;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string userName = 5;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userName = 5;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 5;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 5;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userName_ = value;
        onChanged();
        return this;
      }

      // optional int32 vip = 6;
      private int vip_ ;
      /**
       * <code>optional int32 vip = 6;</code>
       */
      public boolean hasVip() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 vip = 6;</code>
       */
      public int getVip() {
        return vip_;
      }
      /**
       * <code>optional int32 vip = 6;</code>
       */
      public Builder setVip(int value) {
        bitField0_ |= 0x00000020;
        vip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 vip = 6;</code>
       */
      public Builder clearVip() {
        bitField0_ = (bitField0_ & ~0x00000020);
        vip_ = 0;
        onChanged();
        return this;
      }

      // optional string s = 7;
      private java.lang.Object s_ = "";
      /**
       * <code>optional string s = 7;</code>
       *
       * <pre>
       *性别
       * </pre>
       */
      public boolean hasS() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string s = 7;</code>
       *
       * <pre>
       *性别
       * </pre>
       */
      public java.lang.String getS() {
        java.lang.Object ref = s_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          s_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s = 7;</code>
       *
       * <pre>
       *性别
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSBytes() {
        java.lang.Object ref = s_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s = 7;</code>
       *
       * <pre>
       *性别
       * </pre>
       */
      public Builder setS(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        s_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s = 7;</code>
       *
       * <pre>
       *性别
       * </pre>
       */
      public Builder clearS() {
        bitField0_ = (bitField0_ & ~0x00000040);
        s_ = getDefaultInstance().getS();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s = 7;</code>
       *
       * <pre>
       *性别
       * </pre>
       */
      public Builder setSBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        s_ = value;
        onChanged();
        return this;
      }

      // optional int64 talkId = 8;
      private long talkId_ ;
      /**
       * <code>optional int64 talkId = 8;</code>
       */
      public boolean hasTalkId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 talkId = 8;</code>
       */
      public long getTalkId() {
        return talkId_;
      }
      /**
       * <code>optional int64 talkId = 8;</code>
       */
      public Builder setTalkId(long value) {
        bitField0_ |= 0x00000080;
        talkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 talkId = 8;</code>
       */
      public Builder clearTalkId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        talkId_ = 0L;
        onChanged();
        return this;
      }

      // optional string talkName = 9;
      private java.lang.Object talkName_ = "";
      /**
       * <code>optional string talkName = 9;</code>
       */
      public boolean hasTalkName() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string talkName = 9;</code>
       */
      public java.lang.String getTalkName() {
        java.lang.Object ref = talkName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          talkName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string talkName = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTalkNameBytes() {
        java.lang.Object ref = talkName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          talkName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string talkName = 9;</code>
       */
      public Builder setTalkName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        talkName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string talkName = 9;</code>
       */
      public Builder clearTalkName() {
        bitField0_ = (bitField0_ & ~0x00000100);
        talkName_ = getDefaultInstance().getTalkName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string talkName = 9;</code>
       */
      public Builder setTalkNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        talkName_ = value;
        onChanged();
        return this;
      }

      // optional int32 hongbao = 10;
      private int hongbao_ ;
      /**
       * <code>optional int32 hongbao = 10;</code>
       */
      public boolean hasHongbao() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 hongbao = 10;</code>
       */
      public int getHongbao() {
        return hongbao_;
      }
      /**
       * <code>optional int32 hongbao = 10;</code>
       */
      public Builder setHongbao(int value) {
        bitField0_ |= 0x00000200;
        hongbao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hongbao = 10;</code>
       */
      public Builder clearHongbao() {
        bitField0_ = (bitField0_ & ~0x00000200);
        hongbao_ = 0;
        onChanged();
        return this;
      }

      // optional int32 hongbaoId = 11;
      private int hongbaoId_ ;
      /**
       * <code>optional int32 hongbaoId = 11;</code>
       */
      public boolean hasHongbaoId() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 hongbaoId = 11;</code>
       */
      public int getHongbaoId() {
        return hongbaoId_;
      }
      /**
       * <code>optional int32 hongbaoId = 11;</code>
       */
      public Builder setHongbaoId(int value) {
        bitField0_ |= 0x00000400;
        hongbaoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hongbaoId = 11;</code>
       */
      public Builder clearHongbaoId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        hongbaoId_ = 0;
        onChanged();
        return this;
      }

      // optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;
      private com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes team_ = com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes, com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.Builder, com.sy599.game.msg.serverPacket.ChatResMsg.TeamResOrBuilder> teamBuilder_;
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      public boolean hasTeam() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      public com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes getTeam() {
        if (teamBuilder_ == null) {
          return team_;
        } else {
          return teamBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      public Builder setTeam(com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes value) {
        if (teamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          team_ = value;
          onChanged();
        } else {
          teamBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      public Builder setTeam(
          com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.Builder builderForValue) {
        if (teamBuilder_ == null) {
          team_ = builderForValue.build();
          onChanged();
        } else {
          teamBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      public Builder mergeTeam(com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes value) {
        if (teamBuilder_ == null) {
          if (((bitField0_ & 0x00000800) == 0x00000800) &&
              team_ != com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.getDefaultInstance()) {
            team_ =
              com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.newBuilder(team_).mergeFrom(value).buildPartial();
          } else {
            team_ = value;
          }
          onChanged();
        } else {
          teamBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      public Builder clearTeam() {
        if (teamBuilder_ == null) {
          team_ = com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.getDefaultInstance();
          onChanged();
        } else {
          teamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      public com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.Builder getTeamBuilder() {
        bitField0_ |= 0x00000800;
        onChanged();
        return getTeamFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      public com.sy599.game.msg.serverPacket.ChatResMsg.TeamResOrBuilder getTeamOrBuilder() {
        if (teamBuilder_ != null) {
          return teamBuilder_.getMessageOrBuilder();
        } else {
          return team_;
        }
      }
      /**
       * <code>optional .com.sy599.game.msg.serverPacket.TeamRes team = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes, com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.Builder, com.sy599.game.msg.serverPacket.ChatResMsg.TeamResOrBuilder> 
          getTeamFieldBuilder() {
        if (teamBuilder_ == null) {
          teamBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes, com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.Builder, com.sy599.game.msg.serverPacket.ChatResMsg.TeamResOrBuilder>(
                  team_,
                  getParentForChildren(),
                  isClean());
          team_ = null;
        }
        return teamBuilder_;
      }

      // optional int32 systemtype = 13;
      private int systemtype_ ;
      /**
       * <code>optional int32 systemtype = 13;</code>
       */
      public boolean hasSystemtype() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 systemtype = 13;</code>
       */
      public int getSystemtype() {
        return systemtype_;
      }
      /**
       * <code>optional int32 systemtype = 13;</code>
       */
      public Builder setSystemtype(int value) {
        bitField0_ |= 0x00001000;
        systemtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 systemtype = 13;</code>
       */
      public Builder clearSystemtype() {
        bitField0_ = (bitField0_ & ~0x00001000);
        systemtype_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.ChatRes)
    }

    static {
      defaultInstance = new ChatRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.ChatRes)
  }

  public interface TeamResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 chapterId = 1;
    /**
     * <code>required int32 chapterId = 1;</code>
     */
    boolean hasChapterId();
    /**
     * <code>required int32 chapterId = 1;</code>
     */
    int getChapterId();

    // required int64 teamId = 2;
    /**
     * <code>required int64 teamId = 2;</code>
     */
    boolean hasTeamId();
    /**
     * <code>required int64 teamId = 2;</code>
     */
    long getTeamId();

    // required string teamName = 3;
    /**
     * <code>required string teamName = 3;</code>
     */
    boolean hasTeamName();
    /**
     * <code>required string teamName = 3;</code>
     */
    java.lang.String getTeamName();
    /**
     * <code>required string teamName = 3;</code>
     */
    com.google.protobuf.ByteString
        getTeamNameBytes();

    // required string chapterName = 4;
    /**
     * <code>required string chapterName = 4;</code>
     */
    boolean hasChapterName();
    /**
     * <code>required string chapterName = 4;</code>
     */
    java.lang.String getChapterName();
    /**
     * <code>required string chapterName = 4;</code>
     */
    com.google.protobuf.ByteString
        getChapterNameBytes();

    // required int32 chapterLevel = 5;
    /**
     * <code>required int32 chapterLevel = 5;</code>
     */
    boolean hasChapterLevel();
    /**
     * <code>required int32 chapterLevel = 5;</code>
     */
    int getChapterLevel();

    // required int32 needFightVal = 6;
    /**
     * <code>required int32 needFightVal = 6;</code>
     */
    boolean hasNeedFightVal();
    /**
     * <code>required int32 needFightVal = 6;</code>
     */
    int getNeedFightVal();

    // required int64 inviteTime = 7;
    /**
     * <code>required int64 inviteTime = 7;</code>
     */
    boolean hasInviteTime();
    /**
     * <code>required int64 inviteTime = 7;</code>
     */
    long getInviteTime();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.TeamRes}
   *
   * <pre>
   *组队
   * </pre>
   */
  public static final class TeamRes extends
      com.google.protobuf.GeneratedMessage
      implements TeamResOrBuilder {
    // Use TeamRes.newBuilder() to construct.
    private TeamRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TeamRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TeamRes defaultInstance;
    public static TeamRes getDefaultInstance() {
      return defaultInstance;
    }

    public TeamRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TeamRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              chapterId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              teamId_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              teamName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              chapterName_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              chapterLevel_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              needFightVal_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              inviteTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_TeamRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_TeamRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.class, com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.Builder.class);
    }

    public static com.google.protobuf.Parser<TeamRes> PARSER =
        new com.google.protobuf.AbstractParser<TeamRes>() {
      public TeamRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TeamRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TeamRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 chapterId = 1;
    public static final int CHAPTERID_FIELD_NUMBER = 1;
    private int chapterId_;
    /**
     * <code>required int32 chapterId = 1;</code>
     */
    public boolean hasChapterId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 chapterId = 1;</code>
     */
    public int getChapterId() {
      return chapterId_;
    }

    // required int64 teamId = 2;
    public static final int TEAMID_FIELD_NUMBER = 2;
    private long teamId_;
    /**
     * <code>required int64 teamId = 2;</code>
     */
    public boolean hasTeamId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 teamId = 2;</code>
     */
    public long getTeamId() {
      return teamId_;
    }

    // required string teamName = 3;
    public static final int TEAMNAME_FIELD_NUMBER = 3;
    private java.lang.Object teamName_;
    /**
     * <code>required string teamName = 3;</code>
     */
    public boolean hasTeamName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string teamName = 3;</code>
     */
    public java.lang.String getTeamName() {
      java.lang.Object ref = teamName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teamName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string teamName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTeamNameBytes() {
      java.lang.Object ref = teamName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string chapterName = 4;
    public static final int CHAPTERNAME_FIELD_NUMBER = 4;
    private java.lang.Object chapterName_;
    /**
     * <code>required string chapterName = 4;</code>
     */
    public boolean hasChapterName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string chapterName = 4;</code>
     */
    public java.lang.String getChapterName() {
      java.lang.Object ref = chapterName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chapterName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string chapterName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getChapterNameBytes() {
      java.lang.Object ref = chapterName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chapterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 chapterLevel = 5;
    public static final int CHAPTERLEVEL_FIELD_NUMBER = 5;
    private int chapterLevel_;
    /**
     * <code>required int32 chapterLevel = 5;</code>
     */
    public boolean hasChapterLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 chapterLevel = 5;</code>
     */
    public int getChapterLevel() {
      return chapterLevel_;
    }

    // required int32 needFightVal = 6;
    public static final int NEEDFIGHTVAL_FIELD_NUMBER = 6;
    private int needFightVal_;
    /**
     * <code>required int32 needFightVal = 6;</code>
     */
    public boolean hasNeedFightVal() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 needFightVal = 6;</code>
     */
    public int getNeedFightVal() {
      return needFightVal_;
    }

    // required int64 inviteTime = 7;
    public static final int INVITETIME_FIELD_NUMBER = 7;
    private long inviteTime_;
    /**
     * <code>required int64 inviteTime = 7;</code>
     */
    public boolean hasInviteTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int64 inviteTime = 7;</code>
     */
    public long getInviteTime() {
      return inviteTime_;
    }

    private void initFields() {
      chapterId_ = 0;
      teamId_ = 0L;
      teamName_ = "";
      chapterName_ = "";
      chapterLevel_ = 0;
      needFightVal_ = 0;
      inviteTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasChapterId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeamId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeamName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChapterName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChapterLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNeedFightVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInviteTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, chapterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, teamId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTeamNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getChapterNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, chapterLevel_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, needFightVal_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, inviteTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chapterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, teamId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTeamNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getChapterNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, chapterLevel_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, needFightVal_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, inviteTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.TeamRes}
     *
     * <pre>
     *组队
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ChatResMsg.TeamResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_TeamRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_TeamRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.class, com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        chapterId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        teamId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        teamName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        chapterName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        chapterLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        needFightVal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        inviteTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ChatResMsg.internal_static_com_sy599_game_msg_serverPacket_TeamRes_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes build() {
        com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes buildPartial() {
        com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes result = new com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.chapterId_ = chapterId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teamId_ = teamId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.teamName_ = teamName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.chapterName_ = chapterName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.chapterLevel_ = chapterLevel_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.needFightVal_ = needFightVal_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.inviteTime_ = inviteTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes other) {
        if (other == com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes.getDefaultInstance()) return this;
        if (other.hasChapterId()) {
          setChapterId(other.getChapterId());
        }
        if (other.hasTeamId()) {
          setTeamId(other.getTeamId());
        }
        if (other.hasTeamName()) {
          bitField0_ |= 0x00000004;
          teamName_ = other.teamName_;
          onChanged();
        }
        if (other.hasChapterName()) {
          bitField0_ |= 0x00000008;
          chapterName_ = other.chapterName_;
          onChanged();
        }
        if (other.hasChapterLevel()) {
          setChapterLevel(other.getChapterLevel());
        }
        if (other.hasNeedFightVal()) {
          setNeedFightVal(other.getNeedFightVal());
        }
        if (other.hasInviteTime()) {
          setInviteTime(other.getInviteTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChapterId()) {
          
          return false;
        }
        if (!hasTeamId()) {
          
          return false;
        }
        if (!hasTeamName()) {
          
          return false;
        }
        if (!hasChapterName()) {
          
          return false;
        }
        if (!hasChapterLevel()) {
          
          return false;
        }
        if (!hasNeedFightVal()) {
          
          return false;
        }
        if (!hasInviteTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ChatResMsg.TeamRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 chapterId = 1;
      private int chapterId_ ;
      /**
       * <code>required int32 chapterId = 1;</code>
       */
      public boolean hasChapterId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 chapterId = 1;</code>
       */
      public int getChapterId() {
        return chapterId_;
      }
      /**
       * <code>required int32 chapterId = 1;</code>
       */
      public Builder setChapterId(int value) {
        bitField0_ |= 0x00000001;
        chapterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 chapterId = 1;</code>
       */
      public Builder clearChapterId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chapterId_ = 0;
        onChanged();
        return this;
      }

      // required int64 teamId = 2;
      private long teamId_ ;
      /**
       * <code>required int64 teamId = 2;</code>
       */
      public boolean hasTeamId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 teamId = 2;</code>
       */
      public long getTeamId() {
        return teamId_;
      }
      /**
       * <code>required int64 teamId = 2;</code>
       */
      public Builder setTeamId(long value) {
        bitField0_ |= 0x00000002;
        teamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 teamId = 2;</code>
       */
      public Builder clearTeamId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teamId_ = 0L;
        onChanged();
        return this;
      }

      // required string teamName = 3;
      private java.lang.Object teamName_ = "";
      /**
       * <code>required string teamName = 3;</code>
       */
      public boolean hasTeamName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string teamName = 3;</code>
       */
      public java.lang.String getTeamName() {
        java.lang.Object ref = teamName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          teamName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string teamName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTeamNameBytes() {
        java.lang.Object ref = teamName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teamName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string teamName = 3;</code>
       */
      public Builder setTeamName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        teamName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string teamName = 3;</code>
       */
      public Builder clearTeamName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        teamName_ = getDefaultInstance().getTeamName();
        onChanged();
        return this;
      }
      /**
       * <code>required string teamName = 3;</code>
       */
      public Builder setTeamNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        teamName_ = value;
        onChanged();
        return this;
      }

      // required string chapterName = 4;
      private java.lang.Object chapterName_ = "";
      /**
       * <code>required string chapterName = 4;</code>
       */
      public boolean hasChapterName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string chapterName = 4;</code>
       */
      public java.lang.String getChapterName() {
        java.lang.Object ref = chapterName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          chapterName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string chapterName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getChapterNameBytes() {
        java.lang.Object ref = chapterName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chapterName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string chapterName = 4;</code>
       */
      public Builder setChapterName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        chapterName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string chapterName = 4;</code>
       */
      public Builder clearChapterName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chapterName_ = getDefaultInstance().getChapterName();
        onChanged();
        return this;
      }
      /**
       * <code>required string chapterName = 4;</code>
       */
      public Builder setChapterNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        chapterName_ = value;
        onChanged();
        return this;
      }

      // required int32 chapterLevel = 5;
      private int chapterLevel_ ;
      /**
       * <code>required int32 chapterLevel = 5;</code>
       */
      public boolean hasChapterLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 chapterLevel = 5;</code>
       */
      public int getChapterLevel() {
        return chapterLevel_;
      }
      /**
       * <code>required int32 chapterLevel = 5;</code>
       */
      public Builder setChapterLevel(int value) {
        bitField0_ |= 0x00000010;
        chapterLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 chapterLevel = 5;</code>
       */
      public Builder clearChapterLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        chapterLevel_ = 0;
        onChanged();
        return this;
      }

      // required int32 needFightVal = 6;
      private int needFightVal_ ;
      /**
       * <code>required int32 needFightVal = 6;</code>
       */
      public boolean hasNeedFightVal() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 needFightVal = 6;</code>
       */
      public int getNeedFightVal() {
        return needFightVal_;
      }
      /**
       * <code>required int32 needFightVal = 6;</code>
       */
      public Builder setNeedFightVal(int value) {
        bitField0_ |= 0x00000020;
        needFightVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 needFightVal = 6;</code>
       */
      public Builder clearNeedFightVal() {
        bitField0_ = (bitField0_ & ~0x00000020);
        needFightVal_ = 0;
        onChanged();
        return this;
      }

      // required int64 inviteTime = 7;
      private long inviteTime_ ;
      /**
       * <code>required int64 inviteTime = 7;</code>
       */
      public boolean hasInviteTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int64 inviteTime = 7;</code>
       */
      public long getInviteTime() {
        return inviteTime_;
      }
      /**
       * <code>required int64 inviteTime = 7;</code>
       */
      public Builder setInviteTime(long value) {
        bitField0_ |= 0x00000040;
        inviteTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 inviteTime = 7;</code>
       */
      public Builder clearInviteTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        inviteTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.TeamRes)
    }

    static {
      defaultInstance = new TeamRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.TeamRes)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_ChatRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_ChatRes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_TeamRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_TeamRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026files/chatResMsg.proto\022\037com.sy599.game" +
      ".msg.serverPacket\"\372\001\n\007ChatRes\022\014\n\004code\030\001 " +
      "\002(\005\022\016\n\006userId\030\002 \001(\003\022\t\n\001c\030\003 \002(\t\022\n\n\002ip\030\004 \001" +
      "(\t\022\020\n\010userName\030\005 \001(\t\022\013\n\003vip\030\006 \001(\005\022\t\n\001s\030\007" +
      " \001(\t\022\016\n\006talkId\030\010 \001(\003\022\020\n\010talkName\030\t \001(\t\022\017" +
      "\n\007hongbao\030\n \001(\005\022\021\n\thongbaoId\030\013 \001(\005\0226\n\004te" +
      "am\030\014 \001(\0132(.com.sy599.game.msg.serverPack" +
      "et.TeamRes\022\022\n\nsystemtype\030\r \001(\005\"\223\001\n\007TeamR" +
      "es\022\021\n\tchapterId\030\001 \002(\005\022\016\n\006teamId\030\002 \002(\003\022\020\n" +
      "\010teamName\030\003 \002(\t\022\023\n\013chapterName\030\004 \002(\t\022\024\n\014",
      "chapterLevel\030\005 \002(\005\022\024\n\014needFightVal\030\006 \002(\005" +
      "\022\022\n\ninviteTime\030\007 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_sy599_game_msg_serverPacket_ChatRes_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_sy599_game_msg_serverPacket_ChatRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_ChatRes_descriptor,
              new java.lang.String[] { "Code", "UserId", "C", "Ip", "UserName", "Vip", "S", "TalkId", "TalkName", "Hongbao", "HongbaoId", "Team", "Systemtype", });
          internal_static_com_sy599_game_msg_serverPacket_TeamRes_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_sy599_game_msg_serverPacket_TeamRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_TeamRes_descriptor,
              new java.lang.String[] { "ChapterId", "TeamId", "TeamName", "ChapterName", "ChapterLevel", "NeedFightVal", "InviteTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
