// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files/chatMsg.proto

package com.sy599.game.msg.serverPacket;

public final class ChatMsg {
  private ChatMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string c = 1;
    /**
     * <code>required string c = 1;</code>
     */
    boolean hasC();
    /**
     * <code>required string c = 1;</code>
     */
    java.lang.String getC();
    /**
     * <code>required string c = 1;</code>
     */
    com.google.protobuf.ByteString
        getCBytes();

    // required int32 code = 2;
    /**
     * <code>required int32 code = 2;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 2;</code>
     */
    int getCode();

    // optional int64 talkId = 3;
    /**
     * <code>optional int64 talkId = 3;</code>
     */
    boolean hasTalkId();
    /**
     * <code>optional int64 talkId = 3;</code>
     */
    long getTalkId();

    // optional int64 talkName = 4;
    /**
     * <code>optional int64 talkName = 4;</code>
     */
    boolean hasTalkName();
    /**
     * <code>optional int64 talkName = 4;</code>
     */
    long getTalkName();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.Chat}
   *
   * <pre>
   *聊天
   * </pre>
   */
  public static final class Chat extends
      com.google.protobuf.GeneratedMessage
      implements ChatOrBuilder {
    // Use Chat.newBuilder() to construct.
    private Chat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Chat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Chat defaultInstance;
    public static Chat getDefaultInstance() {
      return defaultInstance;
    }

    public Chat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Chat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              c_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              code_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              talkId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              talkName_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ChatMsg.internal_static_com_sy599_game_msg_serverPacket_Chat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ChatMsg.internal_static_com_sy599_game_msg_serverPacket_Chat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ChatMsg.Chat.class, com.sy599.game.msg.serverPacket.ChatMsg.Chat.Builder.class);
    }

    public static com.google.protobuf.Parser<Chat> PARSER =
        new com.google.protobuf.AbstractParser<Chat>() {
      public Chat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Chat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Chat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string c = 1;
    public static final int C_FIELD_NUMBER = 1;
    private java.lang.Object c_;
    /**
     * <code>required string c = 1;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string c = 1;</code>
     */
    public java.lang.String getC() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string c = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCBytes() {
      java.lang.Object ref = c_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>required int32 code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    // optional int64 talkId = 3;
    public static final int TALKID_FIELD_NUMBER = 3;
    private long talkId_;
    /**
     * <code>optional int64 talkId = 3;</code>
     */
    public boolean hasTalkId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 talkId = 3;</code>
     */
    public long getTalkId() {
      return talkId_;
    }

    // optional int64 talkName = 4;
    public static final int TALKNAME_FIELD_NUMBER = 4;
    private long talkName_;
    /**
     * <code>optional int64 talkName = 4;</code>
     */
    public boolean hasTalkName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 talkName = 4;</code>
     */
    public long getTalkName() {
      return talkName_;
    }

    private void initFields() {
      c_ = "";
      code_ = 0;
      talkId_ = 0L;
      talkName_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, talkId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, talkName_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, talkId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, talkName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ChatMsg.Chat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ChatMsg.Chat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.Chat}
     *
     * <pre>
     *聊天
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ChatMsg.ChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ChatMsg.internal_static_com_sy599_game_msg_serverPacket_Chat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ChatMsg.internal_static_com_sy599_game_msg_serverPacket_Chat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ChatMsg.Chat.class, com.sy599.game.msg.serverPacket.ChatMsg.Chat.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ChatMsg.Chat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        c_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        talkId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        talkName_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ChatMsg.internal_static_com_sy599_game_msg_serverPacket_Chat_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ChatMsg.Chat getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ChatMsg.Chat.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ChatMsg.Chat build() {
        com.sy599.game.msg.serverPacket.ChatMsg.Chat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ChatMsg.Chat buildPartial() {
        com.sy599.game.msg.serverPacket.ChatMsg.Chat result = new com.sy599.game.msg.serverPacket.ChatMsg.Chat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.c_ = c_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.talkId_ = talkId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.talkName_ = talkName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ChatMsg.Chat) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ChatMsg.Chat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ChatMsg.Chat other) {
        if (other == com.sy599.game.msg.serverPacket.ChatMsg.Chat.getDefaultInstance()) return this;
        if (other.hasC()) {
          bitField0_ |= 0x00000001;
          c_ = other.c_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasTalkId()) {
          setTalkId(other.getTalkId());
        }
        if (other.hasTalkName()) {
          setTalkName(other.getTalkName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasC()) {
          
          return false;
        }
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ChatMsg.Chat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ChatMsg.Chat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string c = 1;
      private java.lang.Object c_ = "";
      /**
       * <code>required string c = 1;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string c = 1;</code>
       */
      public java.lang.String getC() {
        java.lang.Object ref = c_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string c = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCBytes() {
        java.lang.Object ref = c_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string c = 1;</code>
       */
      public Builder setC(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string c = 1;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c_ = getDefaultInstance().getC();
        onChanged();
        return this;
      }
      /**
       * <code>required string c = 1;</code>
       */
      public Builder setCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c_ = value;
        onChanged();
        return this;
      }

      // required int32 code = 2;
      private int code_ ;
      /**
       * <code>required int32 code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 2;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      // optional int64 talkId = 3;
      private long talkId_ ;
      /**
       * <code>optional int64 talkId = 3;</code>
       */
      public boolean hasTalkId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 talkId = 3;</code>
       */
      public long getTalkId() {
        return talkId_;
      }
      /**
       * <code>optional int64 talkId = 3;</code>
       */
      public Builder setTalkId(long value) {
        bitField0_ |= 0x00000004;
        talkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 talkId = 3;</code>
       */
      public Builder clearTalkId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        talkId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 talkName = 4;
      private long talkName_ ;
      /**
       * <code>optional int64 talkName = 4;</code>
       */
      public boolean hasTalkName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 talkName = 4;</code>
       */
      public long getTalkName() {
        return talkName_;
      }
      /**
       * <code>optional int64 talkName = 4;</code>
       */
      public Builder setTalkName(long value) {
        bitField0_ |= 0x00000008;
        talkName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 talkName = 4;</code>
       */
      public Builder clearTalkName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        talkName_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.Chat)
    }

    static {
      defaultInstance = new Chat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.Chat)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_Chat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_Chat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023files/chatMsg.proto\022\037com.sy599.game.ms" +
      "g.serverPacket\"A\n\004Chat\022\t\n\001c\030\001 \002(\t\022\014\n\004cod" +
      "e\030\002 \002(\005\022\016\n\006talkId\030\003 \001(\003\022\020\n\010talkName\030\004 \001(" +
      "\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_sy599_game_msg_serverPacket_Chat_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_sy599_game_msg_serverPacket_Chat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_Chat_descriptor,
              new java.lang.String[] { "C", "Code", "TalkId", "TalkName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
