// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files/comMsg.proto

package com.sy599.game.msg.serverPacket;

public final class ComMsg {
  private ComMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ComResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 code = 1;
    /**
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     */
    int getCode();

    // repeated int32 params = 2;
    /**
     * <code>repeated int32 params = 2;</code>
     */
    java.util.List<java.lang.Integer> getParamsList();
    /**
     * <code>repeated int32 params = 2;</code>
     */
    int getParamsCount();
    /**
     * <code>repeated int32 params = 2;</code>
     */
    int getParams(int index);

    // repeated string strParams = 3;
    /**
     * <code>repeated string strParams = 3;</code>
     */
    java.util.List<java.lang.String>
    getStrParamsList();
    /**
     * <code>repeated string strParams = 3;</code>
     */
    int getStrParamsCount();
    /**
     * <code>repeated string strParams = 3;</code>
     */
    java.lang.String getStrParams(int index);
    /**
     * <code>repeated string strParams = 3;</code>
     */
    com.google.protobuf.ByteString
        getStrParamsBytes(int index);
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.ComRes}
   */
  public static final class ComRes extends
      com.google.protobuf.GeneratedMessage
      implements ComResOrBuilder {
    // Use ComRes.newBuilder() to construct.
    private ComRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ComRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ComRes defaultInstance;
    public static ComRes getDefaultInstance() {
      return defaultInstance;
    }

    public ComRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ComRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                params_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              params_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                params_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                params_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                strParams_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              strParams_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          strParams_ = new com.google.protobuf.UnmodifiableLazyStringList(strParams_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ComMsg.ComRes.class, com.sy599.game.msg.serverPacket.ComMsg.ComRes.Builder.class);
    }

    public static com.google.protobuf.Parser<ComRes> PARSER =
        new com.google.protobuf.AbstractParser<ComRes>() {
      public ComRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ComRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    // repeated int32 params = 2;
    public static final int PARAMS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> params_;
    /**
     * <code>repeated int32 params = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated int32 params = 2;</code>
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated int32 params = 2;</code>
     */
    public int getParams(int index) {
      return params_.get(index);
    }

    // repeated string strParams = 3;
    public static final int STRPARAMS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList strParams_;
    /**
     * <code>repeated string strParams = 3;</code>
     */
    public java.util.List<java.lang.String>
        getStrParamsList() {
      return strParams_;
    }
    /**
     * <code>repeated string strParams = 3;</code>
     */
    public int getStrParamsCount() {
      return strParams_.size();
    }
    /**
     * <code>repeated string strParams = 3;</code>
     */
    public java.lang.String getStrParams(int index) {
      return strParams_.get(index);
    }
    /**
     * <code>repeated string strParams = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrParamsBytes(int index) {
      return strParams_.getByteString(index);
    }

    private void initFields() {
      code_ = 0;
      params_ = java.util.Collections.emptyList();
      strParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeInt32(2, params_.get(i));
      }
      for (int i = 0; i < strParams_.size(); i++) {
        output.writeBytes(3, strParams_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(params_.get(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < strParams_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(strParams_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStrParamsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ComMsg.ComRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.ComRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ComMsg.ComResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ComMsg.ComRes.class, com.sy599.game.msg.serverPacket.ComMsg.ComRes.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ComMsg.ComRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        strParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComRes_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ComMsg.ComRes getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ComMsg.ComRes.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ComMsg.ComRes build() {
        com.sy599.game.msg.serverPacket.ComMsg.ComRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ComMsg.ComRes buildPartial() {
        com.sy599.game.msg.serverPacket.ComMsg.ComRes result = new com.sy599.game.msg.serverPacket.ComMsg.ComRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = java.util.Collections.unmodifiableList(params_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.params_ = params_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          strParams_ = new com.google.protobuf.UnmodifiableLazyStringList(
              strParams_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.strParams_ = strParams_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ComMsg.ComRes) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ComMsg.ComRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ComMsg.ComRes other) {
        if (other == com.sy599.game.msg.serverPacket.ComMsg.ComRes.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        if (!other.strParams_.isEmpty()) {
          if (strParams_.isEmpty()) {
            strParams_ = other.strParams_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStrParamsIsMutable();
            strParams_.addAll(other.strParams_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ComMsg.ComRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ComMsg.ComRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 code = 1;
      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 params = 2;
      private java.util.List<java.lang.Integer> params_ = java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = new java.util.ArrayList<java.lang.Integer>(params_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getParamsList() {
        return java.util.Collections.unmodifiableList(params_);
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public int getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public Builder setParams(
          int index, int value) {
        ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public Builder addParams(int value) {
        ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureParamsIsMutable();
        super.addAll(values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public Builder clearParams() {
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // repeated string strParams = 3;
      private com.google.protobuf.LazyStringList strParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStrParamsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          strParams_ = new com.google.protobuf.LazyStringArrayList(strParams_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public java.util.List<java.lang.String>
          getStrParamsList() {
        return java.util.Collections.unmodifiableList(strParams_);
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public int getStrParamsCount() {
        return strParams_.size();
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public java.lang.String getStrParams(int index) {
        return strParams_.get(index);
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStrParamsBytes(int index) {
        return strParams_.getByteString(index);
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder setStrParams(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrParamsIsMutable();
        strParams_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder addStrParams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrParamsIsMutable();
        strParams_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder addAllStrParams(
          java.lang.Iterable<java.lang.String> values) {
        ensureStrParamsIsMutable();
        super.addAll(values, strParams_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder clearStrParams() {
        strParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder addStrParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrParamsIsMutable();
        strParams_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.ComRes)
    }

    static {
      defaultInstance = new ComRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.ComRes)
  }

  public interface ComReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 code = 1;
    /**
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     */
    int getCode();

    // repeated int32 params = 2;
    /**
     * <code>repeated int32 params = 2;</code>
     */
    java.util.List<java.lang.Integer> getParamsList();
    /**
     * <code>repeated int32 params = 2;</code>
     */
    int getParamsCount();
    /**
     * <code>repeated int32 params = 2;</code>
     */
    int getParams(int index);

    // repeated string strParams = 3;
    /**
     * <code>repeated string strParams = 3;</code>
     */
    java.util.List<java.lang.String>
    getStrParamsList();
    /**
     * <code>repeated string strParams = 3;</code>
     */
    int getStrParamsCount();
    /**
     * <code>repeated string strParams = 3;</code>
     */
    java.lang.String getStrParams(int index);
    /**
     * <code>repeated string strParams = 3;</code>
     */
    com.google.protobuf.ByteString
        getStrParamsBytes(int index);

    // optional int32 optType = 4;
    /**
     * <code>optional int32 optType = 4;</code>
     *
     * <pre>
     *用于定义操作类型
     * </pre>
     */
    boolean hasOptType();
    /**
     * <code>optional int32 optType = 4;</code>
     *
     * <pre>
     *用于定义操作类型
     * </pre>
     */
    int getOptType();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.ComReq}
   *
   * <pre>
   *通用消息
   * </pre>
   */
  public static final class ComReq extends
      com.google.protobuf.GeneratedMessage
      implements ComReqOrBuilder {
    // Use ComReq.newBuilder() to construct.
    private ComReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ComReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ComReq defaultInstance;
    public static ComReq getDefaultInstance() {
      return defaultInstance;
    }

    public ComReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ComReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                params_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              params_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                params_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                params_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                strParams_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              strParams_.add(input.readBytes());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              optType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          strParams_ = new com.google.protobuf.UnmodifiableLazyStringList(strParams_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ComMsg.ComReq.class, com.sy599.game.msg.serverPacket.ComMsg.ComReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ComReq> PARSER =
        new com.google.protobuf.AbstractParser<ComReq>() {
      public ComReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ComReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    // repeated int32 params = 2;
    public static final int PARAMS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> params_;
    /**
     * <code>repeated int32 params = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated int32 params = 2;</code>
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated int32 params = 2;</code>
     */
    public int getParams(int index) {
      return params_.get(index);
    }

    // repeated string strParams = 3;
    public static final int STRPARAMS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList strParams_;
    /**
     * <code>repeated string strParams = 3;</code>
     */
    public java.util.List<java.lang.String>
        getStrParamsList() {
      return strParams_;
    }
    /**
     * <code>repeated string strParams = 3;</code>
     */
    public int getStrParamsCount() {
      return strParams_.size();
    }
    /**
     * <code>repeated string strParams = 3;</code>
     */
    public java.lang.String getStrParams(int index) {
      return strParams_.get(index);
    }
    /**
     * <code>repeated string strParams = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrParamsBytes(int index) {
      return strParams_.getByteString(index);
    }

    // optional int32 optType = 4;
    public static final int OPTTYPE_FIELD_NUMBER = 4;
    private int optType_;
    /**
     * <code>optional int32 optType = 4;</code>
     *
     * <pre>
     *用于定义操作类型
     * </pre>
     */
    public boolean hasOptType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 optType = 4;</code>
     *
     * <pre>
     *用于定义操作类型
     * </pre>
     */
    public int getOptType() {
      return optType_;
    }

    private void initFields() {
      code_ = 0;
      params_ = java.util.Collections.emptyList();
      strParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      optType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeInt32(2, params_.get(i));
      }
      for (int i = 0; i < strParams_.size(); i++) {
        output.writeBytes(3, strParams_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, optType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(params_.get(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < strParams_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(strParams_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStrParamsList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, optType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.ComReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ComMsg.ComReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.ComReq}
     *
     * <pre>
     *通用消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ComMsg.ComReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ComMsg.ComReq.class, com.sy599.game.msg.serverPacket.ComMsg.ComReq.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ComMsg.ComReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        strParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        optType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_ComReq_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ComMsg.ComReq getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ComMsg.ComReq.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ComMsg.ComReq build() {
        com.sy599.game.msg.serverPacket.ComMsg.ComReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ComMsg.ComReq buildPartial() {
        com.sy599.game.msg.serverPacket.ComMsg.ComReq result = new com.sy599.game.msg.serverPacket.ComMsg.ComReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = java.util.Collections.unmodifiableList(params_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.params_ = params_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          strParams_ = new com.google.protobuf.UnmodifiableLazyStringList(
              strParams_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.strParams_ = strParams_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.optType_ = optType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ComMsg.ComReq) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ComMsg.ComReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ComMsg.ComReq other) {
        if (other == com.sy599.game.msg.serverPacket.ComMsg.ComReq.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        if (!other.strParams_.isEmpty()) {
          if (strParams_.isEmpty()) {
            strParams_ = other.strParams_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStrParamsIsMutable();
            strParams_.addAll(other.strParams_);
          }
          onChanged();
        }
        if (other.hasOptType()) {
          setOptType(other.getOptType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ComMsg.ComReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ComMsg.ComReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 code = 1;
      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 params = 2;
      private java.util.List<java.lang.Integer> params_ = java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          params_ = new java.util.ArrayList<java.lang.Integer>(params_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getParamsList() {
        return java.util.Collections.unmodifiableList(params_);
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public int getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public Builder setParams(
          int index, int value) {
        ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public Builder addParams(int value) {
        ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureParamsIsMutable();
        super.addAll(values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       */
      public Builder clearParams() {
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // repeated string strParams = 3;
      private com.google.protobuf.LazyStringList strParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStrParamsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          strParams_ = new com.google.protobuf.LazyStringArrayList(strParams_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public java.util.List<java.lang.String>
          getStrParamsList() {
        return java.util.Collections.unmodifiableList(strParams_);
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public int getStrParamsCount() {
        return strParams_.size();
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public java.lang.String getStrParams(int index) {
        return strParams_.get(index);
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStrParamsBytes(int index) {
        return strParams_.getByteString(index);
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder setStrParams(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrParamsIsMutable();
        strParams_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder addStrParams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrParamsIsMutable();
        strParams_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder addAllStrParams(
          java.lang.Iterable<java.lang.String> values) {
        ensureStrParamsIsMutable();
        super.addAll(values, strParams_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder clearStrParams() {
        strParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strParams = 3;</code>
       */
      public Builder addStrParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrParamsIsMutable();
        strParams_.add(value);
        onChanged();
        return this;
      }

      // optional int32 optType = 4;
      private int optType_ ;
      /**
       * <code>optional int32 optType = 4;</code>
       *
       * <pre>
       *用于定义操作类型
       * </pre>
       */
      public boolean hasOptType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 optType = 4;</code>
       *
       * <pre>
       *用于定义操作类型
       * </pre>
       */
      public int getOptType() {
        return optType_;
      }
      /**
       * <code>optional int32 optType = 4;</code>
       *
       * <pre>
       *用于定义操作类型
       * </pre>
       */
      public Builder setOptType(int value) {
        bitField0_ |= 0x00000008;
        optType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 optType = 4;</code>
       *
       * <pre>
       *用于定义操作类型
       * </pre>
       */
      public Builder clearOptType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        optType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.ComReq)
    }

    static {
      defaultInstance = new ComReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.ComReq)
  }

  public interface PingResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 t = 1;
    /**
     * <code>optional int32 t = 1;</code>
     */
    boolean hasT();
    /**
     * <code>optional int32 t = 1;</code>
     */
    int getT();

    // optional string v = 2;
    /**
     * <code>optional string v = 2;</code>
     */
    boolean hasV();
    /**
     * <code>optional string v = 2;</code>
     */
    java.lang.String getV();
    /**
     * <code>optional string v = 2;</code>
     */
    com.google.protobuf.ByteString
        getVBytes();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.PingRes}
   */
  public static final class PingRes extends
      com.google.protobuf.GeneratedMessage
      implements PingResOrBuilder {
    // Use PingRes.newBuilder() to construct.
    private PingRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PingRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PingRes defaultInstance;
    public static PingRes getDefaultInstance() {
      return defaultInstance;
    }

    public PingRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PingRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              t_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              v_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_PingRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_PingRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ComMsg.PingRes.class, com.sy599.game.msg.serverPacket.ComMsg.PingRes.Builder.class);
    }

    public static com.google.protobuf.Parser<PingRes> PARSER =
        new com.google.protobuf.AbstractParser<PingRes>() {
      public PingRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PingRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PingRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 t = 1;
    public static final int T_FIELD_NUMBER = 1;
    private int t_;
    /**
     * <code>optional int32 t = 1;</code>
     */
    public boolean hasT() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 t = 1;</code>
     */
    public int getT() {
      return t_;
    }

    // optional string v = 2;
    public static final int V_FIELD_NUMBER = 2;
    private java.lang.Object v_;
    /**
     * <code>optional string v = 2;</code>
     */
    public boolean hasV() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string v = 2;</code>
     */
    public java.lang.String getV() {
      java.lang.Object ref = v_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          v_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string v = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVBytes() {
      java.lang.Object ref = v_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        v_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      t_ = 0;
      v_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, t_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, t_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ComMsg.PingRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ComMsg.PingRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.PingRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ComMsg.PingResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_PingRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_PingRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ComMsg.PingRes.class, com.sy599.game.msg.serverPacket.ComMsg.PingRes.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ComMsg.PingRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        t_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        v_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ComMsg.internal_static_com_sy599_game_msg_serverPacket_PingRes_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ComMsg.PingRes getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ComMsg.PingRes.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ComMsg.PingRes build() {
        com.sy599.game.msg.serverPacket.ComMsg.PingRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ComMsg.PingRes buildPartial() {
        com.sy599.game.msg.serverPacket.ComMsg.PingRes result = new com.sy599.game.msg.serverPacket.ComMsg.PingRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.t_ = t_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.v_ = v_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ComMsg.PingRes) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ComMsg.PingRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ComMsg.PingRes other) {
        if (other == com.sy599.game.msg.serverPacket.ComMsg.PingRes.getDefaultInstance()) return this;
        if (other.hasT()) {
          setT(other.getT());
        }
        if (other.hasV()) {
          bitField0_ |= 0x00000002;
          v_ = other.v_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ComMsg.PingRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ComMsg.PingRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 t = 1;
      private int t_ ;
      /**
       * <code>optional int32 t = 1;</code>
       */
      public boolean hasT() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 t = 1;</code>
       */
      public int getT() {
        return t_;
      }
      /**
       * <code>optional int32 t = 1;</code>
       */
      public Builder setT(int value) {
        bitField0_ |= 0x00000001;
        t_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 t = 1;</code>
       */
      public Builder clearT() {
        bitField0_ = (bitField0_ & ~0x00000001);
        t_ = 0;
        onChanged();
        return this;
      }

      // optional string v = 2;
      private java.lang.Object v_ = "";
      /**
       * <code>optional string v = 2;</code>
       */
      public boolean hasV() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string v = 2;</code>
       */
      public java.lang.String getV() {
        java.lang.Object ref = v_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          v_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string v = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVBytes() {
        java.lang.Object ref = v_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          v_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string v = 2;</code>
       */
      public Builder setV(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string v = 2;</code>
       */
      public Builder clearV() {
        bitField0_ = (bitField0_ & ~0x00000002);
        v_ = getDefaultInstance().getV();
        onChanged();
        return this;
      }
      /**
       * <code>optional string v = 2;</code>
       */
      public Builder setVBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        v_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.PingRes)
    }

    static {
      defaultInstance = new PingRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.PingRes)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_ComRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_ComRes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_ComReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_ComReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_PingRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_PingRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022files/comMsg.proto\022\037com.sy599.game.msg" +
      ".serverPacket\"9\n\006ComRes\022\014\n\004code\030\001 \002(\005\022\016\n" +
      "\006params\030\002 \003(\005\022\021\n\tstrParams\030\003 \003(\t\"J\n\006ComR" +
      "eq\022\014\n\004code\030\001 \002(\005\022\016\n\006params\030\002 \003(\005\022\021\n\tstrP" +
      "arams\030\003 \003(\t\022\017\n\007optType\030\004 \001(\005\"\037\n\007PingRes\022" +
      "\t\n\001t\030\001 \001(\005\022\t\n\001v\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_sy599_game_msg_serverPacket_ComRes_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_sy599_game_msg_serverPacket_ComRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_ComRes_descriptor,
              new java.lang.String[] { "Code", "Params", "StrParams", });
          internal_static_com_sy599_game_msg_serverPacket_ComReq_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_sy599_game_msg_serverPacket_ComReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_ComReq_descriptor,
              new java.lang.String[] { "Code", "Params", "StrParams", "OptType", });
          internal_static_com_sy599_game_msg_serverPacket_PingRes_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_sy599_game_msg_serverPacket_PingRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_PingRes_descriptor,
              new java.lang.String[] { "T", "V", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
