// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files/ConfigMsg.proto

package com.sy599.game.msg.serverPacket;

public final class ConfigMsg {
  private ConfigMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConfigInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    java.util.List<com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes> 
        getSignList();
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes getSign(int index);
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    int getSignCount();
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    java.util.List<? extends com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder> 
        getSignOrBuilderList();
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder getSignOrBuilder(
        int index);

    // required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;
    /**
     * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
     */
    boolean hasAloneConfig();
    /**
     * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
     */
    com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes getAloneConfig();
    /**
     * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
     */
    com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigResOrBuilder getAloneConfigOrBuilder();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.ConfigInfo}
   *
   * <pre>
   *配置信息
   * </pre>
   */
  public static final class ConfigInfo extends
      com.google.protobuf.GeneratedMessage
      implements ConfigInfoOrBuilder {
    // Use ConfigInfo.newBuilder() to construct.
    private ConfigInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConfigInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConfigInfo defaultInstance;
    public static ConfigInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ConfigInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sign_ = new java.util.ArrayList<com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes>();
                mutable_bitField0_ |= 0x00000001;
              }
              sign_.add(input.readMessage(com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = aloneConfig_.toBuilder();
              }
              aloneConfig_ = input.readMessage(com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(aloneConfig_);
                aloneConfig_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sign_ = java.util.Collections.unmodifiableList(sign_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo.class, com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ConfigInfo> PARSER =
        new com.google.protobuf.AbstractParser<ConfigInfo>() {
      public ConfigInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;
    public static final int SIGN_FIELD_NUMBER = 1;
    private java.util.List<com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes> sign_;
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    public java.util.List<com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes> getSignList() {
      return sign_;
    }
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    public java.util.List<? extends com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder> 
        getSignOrBuilderList() {
      return sign_;
    }
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    public int getSignCount() {
      return sign_.size();
    }
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes getSign(int index) {
      return sign_.get(index);
    }
    /**
     * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
     */
    public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder getSignOrBuilder(
        int index) {
      return sign_.get(index);
    }

    // required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;
    public static final int ALONECONFIG_FIELD_NUMBER = 3;
    private com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes aloneConfig_;
    /**
     * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
     */
    public boolean hasAloneConfig() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
     */
    public com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes getAloneConfig() {
      return aloneConfig_;
    }
    /**
     * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
     */
    public com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigResOrBuilder getAloneConfigOrBuilder() {
      return aloneConfig_;
    }

    private void initFields() {
      sign_ = java.util.Collections.emptyList();
      aloneConfig_ = com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAloneConfig()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSignCount(); i++) {
        if (!getSign(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getAloneConfig().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sign_.size(); i++) {
        output.writeMessage(1, sign_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(3, aloneConfig_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sign_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sign_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, aloneConfig_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.ConfigInfo}
     *
     * <pre>
     *配置信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo.class, com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSignFieldBuilder();
          getAloneConfigFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (signBuilder_ == null) {
          sign_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          signBuilder_.clear();
        }
        if (aloneConfigBuilder_ == null) {
          aloneConfig_ = com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.getDefaultInstance();
        } else {
          aloneConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo build() {
        com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo buildPartial() {
        com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo result = new com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (signBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sign_ = java.util.Collections.unmodifiableList(sign_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sign_ = sign_;
        } else {
          result.sign_ = signBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (aloneConfigBuilder_ == null) {
          result.aloneConfig_ = aloneConfig_;
        } else {
          result.aloneConfig_ = aloneConfigBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo other) {
        if (other == com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo.getDefaultInstance()) return this;
        if (signBuilder_ == null) {
          if (!other.sign_.isEmpty()) {
            if (sign_.isEmpty()) {
              sign_ = other.sign_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSignIsMutable();
              sign_.addAll(other.sign_);
            }
            onChanged();
          }
        } else {
          if (!other.sign_.isEmpty()) {
            if (signBuilder_.isEmpty()) {
              signBuilder_.dispose();
              signBuilder_ = null;
              sign_ = other.sign_;
              bitField0_ = (bitField0_ & ~0x00000001);
              signBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSignFieldBuilder() : null;
            } else {
              signBuilder_.addAllMessages(other.sign_);
            }
          }
        }
        if (other.hasAloneConfig()) {
          mergeAloneConfig(other.getAloneConfig());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAloneConfig()) {
          
          return false;
        }
        for (int i = 0; i < getSignCount(); i++) {
          if (!getSign(i).isInitialized()) {
            
            return false;
          }
        }
        if (!getAloneConfig().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ConfigMsg.ConfigInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;
      private java.util.List<com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes> sign_ =
        java.util.Collections.emptyList();
      private void ensureSignIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sign_ = new java.util.ArrayList<com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes>(sign_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder> signBuilder_;

      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public java.util.List<com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes> getSignList() {
        if (signBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sign_);
        } else {
          return signBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public int getSignCount() {
        if (signBuilder_ == null) {
          return sign_.size();
        } else {
          return signBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes getSign(int index) {
        if (signBuilder_ == null) {
          return sign_.get(index);
        } else {
          return signBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder setSign(
          int index, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes value) {
        if (signBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignIsMutable();
          sign_.set(index, value);
          onChanged();
        } else {
          signBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder setSign(
          int index, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder builderForValue) {
        if (signBuilder_ == null) {
          ensureSignIsMutable();
          sign_.set(index, builderForValue.build());
          onChanged();
        } else {
          signBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder addSign(com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes value) {
        if (signBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignIsMutable();
          sign_.add(value);
          onChanged();
        } else {
          signBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder addSign(
          int index, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes value) {
        if (signBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignIsMutable();
          sign_.add(index, value);
          onChanged();
        } else {
          signBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder addSign(
          com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder builderForValue) {
        if (signBuilder_ == null) {
          ensureSignIsMutable();
          sign_.add(builderForValue.build());
          onChanged();
        } else {
          signBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder addSign(
          int index, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder builderForValue) {
        if (signBuilder_ == null) {
          ensureSignIsMutable();
          sign_.add(index, builderForValue.build());
          onChanged();
        } else {
          signBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder addAllSign(
          java.lang.Iterable<? extends com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes> values) {
        if (signBuilder_ == null) {
          ensureSignIsMutable();
          super.addAll(values, sign_);
          onChanged();
        } else {
          signBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder clearSign() {
        if (signBuilder_ == null) {
          sign_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          signBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public Builder removeSign(int index) {
        if (signBuilder_ == null) {
          ensureSignIsMutable();
          sign_.remove(index);
          onChanged();
        } else {
          signBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder getSignBuilder(
          int index) {
        return getSignFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder getSignOrBuilder(
          int index) {
        if (signBuilder_ == null) {
          return sign_.get(index);  } else {
          return signBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public java.util.List<? extends com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder> 
           getSignOrBuilderList() {
        if (signBuilder_ != null) {
          return signBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sign_);
        }
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder addSignBuilder() {
        return getSignFieldBuilder().addBuilder(
            com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder addSignBuilder(
          int index) {
        return getSignFieldBuilder().addBuilder(
            index, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sy599.game.msg.serverPacket.SevenGoldConfigRes sign = 1;</code>
       */
      public java.util.List<com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder> 
           getSignBuilderList() {
        return getSignFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder> 
          getSignFieldBuilder() {
        if (signBuilder_ == null) {
          signBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder>(
                  sign_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sign_ = null;
        }
        return signBuilder_;
      }

      // required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;
      private com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes aloneConfig_ = com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes, com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.Builder, com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigResOrBuilder> aloneConfigBuilder_;
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      public boolean hasAloneConfig() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      public com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes getAloneConfig() {
        if (aloneConfigBuilder_ == null) {
          return aloneConfig_;
        } else {
          return aloneConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      public Builder setAloneConfig(com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes value) {
        if (aloneConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          aloneConfig_ = value;
          onChanged();
        } else {
          aloneConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      public Builder setAloneConfig(
          com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.Builder builderForValue) {
        if (aloneConfigBuilder_ == null) {
          aloneConfig_ = builderForValue.build();
          onChanged();
        } else {
          aloneConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      public Builder mergeAloneConfig(com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes value) {
        if (aloneConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              aloneConfig_ != com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.getDefaultInstance()) {
            aloneConfig_ =
              com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.newBuilder(aloneConfig_).mergeFrom(value).buildPartial();
          } else {
            aloneConfig_ = value;
          }
          onChanged();
        } else {
          aloneConfigBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      public Builder clearAloneConfig() {
        if (aloneConfigBuilder_ == null) {
          aloneConfig_ = com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.getDefaultInstance();
          onChanged();
        } else {
          aloneConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      public com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.Builder getAloneConfigBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getAloneConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      public com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigResOrBuilder getAloneConfigOrBuilder() {
        if (aloneConfigBuilder_ != null) {
          return aloneConfigBuilder_.getMessageOrBuilder();
        } else {
          return aloneConfig_;
        }
      }
      /**
       * <code>required .com.sy599.game.msg.serverPacket.AloneConfigRes aloneConfig = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes, com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.Builder, com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigResOrBuilder> 
          getAloneConfigFieldBuilder() {
        if (aloneConfigBuilder_ == null) {
          aloneConfigBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes, com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.Builder, com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigResOrBuilder>(
                  aloneConfig_,
                  getParentForChildren(),
                  isClean());
          aloneConfig_ = null;
        }
        return aloneConfigBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.ConfigInfo)
    }

    static {
      defaultInstance = new ConfigInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.ConfigInfo)
  }

  public interface AloneConfigResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 share = 1;
    /**
     * <code>required int32 share = 1;</code>
     *
     * <pre>
     *分享
     * </pre>
     */
    boolean hasShare();
    /**
     * <code>required int32 share = 1;</code>
     *
     * <pre>
     *分享
     * </pre>
     */
    int getShare();

    // required int32 broke = 2;
    /**
     * <code>required int32 broke = 2;</code>
     *
     * <pre>
     *破产
     * </pre>
     */
    boolean hasBroke();
    /**
     * <code>required int32 broke = 2;</code>
     *
     * <pre>
     *破产
     * </pre>
     */
    int getBroke();

    // required int32 brokeShare = 3;
    /**
     * <code>required int32 brokeShare = 3;</code>
     *
     * <pre>
     *破产弹出的分享
     * </pre>
     */
    boolean hasBrokeShare();
    /**
     * <code>required int32 brokeShare = 3;</code>
     *
     * <pre>
     *破产弹出的分享
     * </pre>
     */
    int getBrokeShare();

    // required int32 bingDingNum = 4;
    /**
     * <code>required int32 bingDingNum = 4;</code>
     *
     * <pre>
     *绑定成功获取豆子
     * </pre>
     */
    boolean hasBingDingNum();
    /**
     * <code>required int32 bingDingNum = 4;</code>
     *
     * <pre>
     *绑定成功获取豆子
     * </pre>
     */
    int getBingDingNum();

    // required int32 brokeTigger = 5;
    /**
     * <code>required int32 brokeTigger = 5;</code>
     *
     * <pre>
     *破产下限触发
     * </pre>
     */
    boolean hasBrokeTigger();
    /**
     * <code>required int32 brokeTigger = 5;</code>
     *
     * <pre>
     *破产下限触发
     * </pre>
     */
    int getBrokeTigger();

    // required int32 videoWatchNum = 6;
    /**
     * <code>required int32 videoWatchNum = 6;</code>
     *
     * <pre>
     *视频奖励次数
     * </pre>
     */
    boolean hasVideoWatchNum();
    /**
     * <code>required int32 videoWatchNum = 6;</code>
     *
     * <pre>
     *视频奖励次数
     * </pre>
     */
    int getVideoWatchNum();

    // required int32 videoAwardNum = 7;
    /**
     * <code>required int32 videoAwardNum = 7;</code>
     *
     * <pre>
     *视频奖励数量
     * </pre>
     */
    boolean hasVideoAwardNum();
    /**
     * <code>required int32 videoAwardNum = 7;</code>
     *
     * <pre>
     *视频奖励数量
     * </pre>
     */
    int getVideoAwardNum();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.AloneConfigRes}
   *
   * <pre>
   *非列表的单独配置放此处
   * </pre>
   */
  public static final class AloneConfigRes extends
      com.google.protobuf.GeneratedMessage
      implements AloneConfigResOrBuilder {
    // Use AloneConfigRes.newBuilder() to construct.
    private AloneConfigRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AloneConfigRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AloneConfigRes defaultInstance;
    public static AloneConfigRes getDefaultInstance() {
      return defaultInstance;
    }

    public AloneConfigRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AloneConfigRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              share_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              broke_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              brokeShare_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              bingDingNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              brokeTigger_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              videoWatchNum_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              videoAwardNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.class, com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.Builder.class);
    }

    public static com.google.protobuf.Parser<AloneConfigRes> PARSER =
        new com.google.protobuf.AbstractParser<AloneConfigRes>() {
      public AloneConfigRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AloneConfigRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AloneConfigRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 share = 1;
    public static final int SHARE_FIELD_NUMBER = 1;
    private int share_;
    /**
     * <code>required int32 share = 1;</code>
     *
     * <pre>
     *分享
     * </pre>
     */
    public boolean hasShare() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 share = 1;</code>
     *
     * <pre>
     *分享
     * </pre>
     */
    public int getShare() {
      return share_;
    }

    // required int32 broke = 2;
    public static final int BROKE_FIELD_NUMBER = 2;
    private int broke_;
    /**
     * <code>required int32 broke = 2;</code>
     *
     * <pre>
     *破产
     * </pre>
     */
    public boolean hasBroke() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 broke = 2;</code>
     *
     * <pre>
     *破产
     * </pre>
     */
    public int getBroke() {
      return broke_;
    }

    // required int32 brokeShare = 3;
    public static final int BROKESHARE_FIELD_NUMBER = 3;
    private int brokeShare_;
    /**
     * <code>required int32 brokeShare = 3;</code>
     *
     * <pre>
     *破产弹出的分享
     * </pre>
     */
    public boolean hasBrokeShare() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 brokeShare = 3;</code>
     *
     * <pre>
     *破产弹出的分享
     * </pre>
     */
    public int getBrokeShare() {
      return brokeShare_;
    }

    // required int32 bingDingNum = 4;
    public static final int BINGDINGNUM_FIELD_NUMBER = 4;
    private int bingDingNum_;
    /**
     * <code>required int32 bingDingNum = 4;</code>
     *
     * <pre>
     *绑定成功获取豆子
     * </pre>
     */
    public boolean hasBingDingNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 bingDingNum = 4;</code>
     *
     * <pre>
     *绑定成功获取豆子
     * </pre>
     */
    public int getBingDingNum() {
      return bingDingNum_;
    }

    // required int32 brokeTigger = 5;
    public static final int BROKETIGGER_FIELD_NUMBER = 5;
    private int brokeTigger_;
    /**
     * <code>required int32 brokeTigger = 5;</code>
     *
     * <pre>
     *破产下限触发
     * </pre>
     */
    public boolean hasBrokeTigger() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 brokeTigger = 5;</code>
     *
     * <pre>
     *破产下限触发
     * </pre>
     */
    public int getBrokeTigger() {
      return brokeTigger_;
    }

    // required int32 videoWatchNum = 6;
    public static final int VIDEOWATCHNUM_FIELD_NUMBER = 6;
    private int videoWatchNum_;
    /**
     * <code>required int32 videoWatchNum = 6;</code>
     *
     * <pre>
     *视频奖励次数
     * </pre>
     */
    public boolean hasVideoWatchNum() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 videoWatchNum = 6;</code>
     *
     * <pre>
     *视频奖励次数
     * </pre>
     */
    public int getVideoWatchNum() {
      return videoWatchNum_;
    }

    // required int32 videoAwardNum = 7;
    public static final int VIDEOAWARDNUM_FIELD_NUMBER = 7;
    private int videoAwardNum_;
    /**
     * <code>required int32 videoAwardNum = 7;</code>
     *
     * <pre>
     *视频奖励数量
     * </pre>
     */
    public boolean hasVideoAwardNum() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 videoAwardNum = 7;</code>
     *
     * <pre>
     *视频奖励数量
     * </pre>
     */
    public int getVideoAwardNum() {
      return videoAwardNum_;
    }

    private void initFields() {
      share_ = 0;
      broke_ = 0;
      brokeShare_ = 0;
      bingDingNum_ = 0;
      brokeTigger_ = 0;
      videoWatchNum_ = 0;
      videoAwardNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasShare()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBroke()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBrokeShare()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBingDingNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBrokeTigger()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVideoWatchNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVideoAwardNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, share_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, broke_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, brokeShare_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, bingDingNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, brokeTigger_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, videoWatchNum_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, videoAwardNum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, share_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, broke_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, brokeShare_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, bingDingNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, brokeTigger_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, videoWatchNum_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, videoAwardNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.AloneConfigRes}
     *
     * <pre>
     *非列表的单独配置放此处
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.class, com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        share_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        broke_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        brokeShare_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        bingDingNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        brokeTigger_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        videoWatchNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        videoAwardNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes build() {
        com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes buildPartial() {
        com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes result = new com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.share_ = share_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.broke_ = broke_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.brokeShare_ = brokeShare_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bingDingNum_ = bingDingNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.brokeTigger_ = brokeTigger_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.videoWatchNum_ = videoWatchNum_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.videoAwardNum_ = videoAwardNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes other) {
        if (other == com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes.getDefaultInstance()) return this;
        if (other.hasShare()) {
          setShare(other.getShare());
        }
        if (other.hasBroke()) {
          setBroke(other.getBroke());
        }
        if (other.hasBrokeShare()) {
          setBrokeShare(other.getBrokeShare());
        }
        if (other.hasBingDingNum()) {
          setBingDingNum(other.getBingDingNum());
        }
        if (other.hasBrokeTigger()) {
          setBrokeTigger(other.getBrokeTigger());
        }
        if (other.hasVideoWatchNum()) {
          setVideoWatchNum(other.getVideoWatchNum());
        }
        if (other.hasVideoAwardNum()) {
          setVideoAwardNum(other.getVideoAwardNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasShare()) {
          
          return false;
        }
        if (!hasBroke()) {
          
          return false;
        }
        if (!hasBrokeShare()) {
          
          return false;
        }
        if (!hasBingDingNum()) {
          
          return false;
        }
        if (!hasBrokeTigger()) {
          
          return false;
        }
        if (!hasVideoWatchNum()) {
          
          return false;
        }
        if (!hasVideoAwardNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ConfigMsg.AloneConfigRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 share = 1;
      private int share_ ;
      /**
       * <code>required int32 share = 1;</code>
       *
       * <pre>
       *分享
       * </pre>
       */
      public boolean hasShare() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 share = 1;</code>
       *
       * <pre>
       *分享
       * </pre>
       */
      public int getShare() {
        return share_;
      }
      /**
       * <code>required int32 share = 1;</code>
       *
       * <pre>
       *分享
       * </pre>
       */
      public Builder setShare(int value) {
        bitField0_ |= 0x00000001;
        share_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 share = 1;</code>
       *
       * <pre>
       *分享
       * </pre>
       */
      public Builder clearShare() {
        bitField0_ = (bitField0_ & ~0x00000001);
        share_ = 0;
        onChanged();
        return this;
      }

      // required int32 broke = 2;
      private int broke_ ;
      /**
       * <code>required int32 broke = 2;</code>
       *
       * <pre>
       *破产
       * </pre>
       */
      public boolean hasBroke() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 broke = 2;</code>
       *
       * <pre>
       *破产
       * </pre>
       */
      public int getBroke() {
        return broke_;
      }
      /**
       * <code>required int32 broke = 2;</code>
       *
       * <pre>
       *破产
       * </pre>
       */
      public Builder setBroke(int value) {
        bitField0_ |= 0x00000002;
        broke_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 broke = 2;</code>
       *
       * <pre>
       *破产
       * </pre>
       */
      public Builder clearBroke() {
        bitField0_ = (bitField0_ & ~0x00000002);
        broke_ = 0;
        onChanged();
        return this;
      }

      // required int32 brokeShare = 3;
      private int brokeShare_ ;
      /**
       * <code>required int32 brokeShare = 3;</code>
       *
       * <pre>
       *破产弹出的分享
       * </pre>
       */
      public boolean hasBrokeShare() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 brokeShare = 3;</code>
       *
       * <pre>
       *破产弹出的分享
       * </pre>
       */
      public int getBrokeShare() {
        return brokeShare_;
      }
      /**
       * <code>required int32 brokeShare = 3;</code>
       *
       * <pre>
       *破产弹出的分享
       * </pre>
       */
      public Builder setBrokeShare(int value) {
        bitField0_ |= 0x00000004;
        brokeShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 brokeShare = 3;</code>
       *
       * <pre>
       *破产弹出的分享
       * </pre>
       */
      public Builder clearBrokeShare() {
        bitField0_ = (bitField0_ & ~0x00000004);
        brokeShare_ = 0;
        onChanged();
        return this;
      }

      // required int32 bingDingNum = 4;
      private int bingDingNum_ ;
      /**
       * <code>required int32 bingDingNum = 4;</code>
       *
       * <pre>
       *绑定成功获取豆子
       * </pre>
       */
      public boolean hasBingDingNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 bingDingNum = 4;</code>
       *
       * <pre>
       *绑定成功获取豆子
       * </pre>
       */
      public int getBingDingNum() {
        return bingDingNum_;
      }
      /**
       * <code>required int32 bingDingNum = 4;</code>
       *
       * <pre>
       *绑定成功获取豆子
       * </pre>
       */
      public Builder setBingDingNum(int value) {
        bitField0_ |= 0x00000008;
        bingDingNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bingDingNum = 4;</code>
       *
       * <pre>
       *绑定成功获取豆子
       * </pre>
       */
      public Builder clearBingDingNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bingDingNum_ = 0;
        onChanged();
        return this;
      }

      // required int32 brokeTigger = 5;
      private int brokeTigger_ ;
      /**
       * <code>required int32 brokeTigger = 5;</code>
       *
       * <pre>
       *破产下限触发
       * </pre>
       */
      public boolean hasBrokeTigger() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 brokeTigger = 5;</code>
       *
       * <pre>
       *破产下限触发
       * </pre>
       */
      public int getBrokeTigger() {
        return brokeTigger_;
      }
      /**
       * <code>required int32 brokeTigger = 5;</code>
       *
       * <pre>
       *破产下限触发
       * </pre>
       */
      public Builder setBrokeTigger(int value) {
        bitField0_ |= 0x00000010;
        brokeTigger_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 brokeTigger = 5;</code>
       *
       * <pre>
       *破产下限触发
       * </pre>
       */
      public Builder clearBrokeTigger() {
        bitField0_ = (bitField0_ & ~0x00000010);
        brokeTigger_ = 0;
        onChanged();
        return this;
      }

      // required int32 videoWatchNum = 6;
      private int videoWatchNum_ ;
      /**
       * <code>required int32 videoWatchNum = 6;</code>
       *
       * <pre>
       *视频奖励次数
       * </pre>
       */
      public boolean hasVideoWatchNum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 videoWatchNum = 6;</code>
       *
       * <pre>
       *视频奖励次数
       * </pre>
       */
      public int getVideoWatchNum() {
        return videoWatchNum_;
      }
      /**
       * <code>required int32 videoWatchNum = 6;</code>
       *
       * <pre>
       *视频奖励次数
       * </pre>
       */
      public Builder setVideoWatchNum(int value) {
        bitField0_ |= 0x00000020;
        videoWatchNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 videoWatchNum = 6;</code>
       *
       * <pre>
       *视频奖励次数
       * </pre>
       */
      public Builder clearVideoWatchNum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        videoWatchNum_ = 0;
        onChanged();
        return this;
      }

      // required int32 videoAwardNum = 7;
      private int videoAwardNum_ ;
      /**
       * <code>required int32 videoAwardNum = 7;</code>
       *
       * <pre>
       *视频奖励数量
       * </pre>
       */
      public boolean hasVideoAwardNum() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 videoAwardNum = 7;</code>
       *
       * <pre>
       *视频奖励数量
       * </pre>
       */
      public int getVideoAwardNum() {
        return videoAwardNum_;
      }
      /**
       * <code>required int32 videoAwardNum = 7;</code>
       *
       * <pre>
       *视频奖励数量
       * </pre>
       */
      public Builder setVideoAwardNum(int value) {
        bitField0_ |= 0x00000040;
        videoAwardNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 videoAwardNum = 7;</code>
       *
       * <pre>
       *视频奖励数量
       * </pre>
       */
      public Builder clearVideoAwardNum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        videoAwardNum_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.AloneConfigRes)
    }

    static {
      defaultInstance = new AloneConfigRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.AloneConfigRes)
  }

  public interface SevenGoldConfigResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required int32 dayNum = 2;
    /**
     * <code>required int32 dayNum = 2;</code>
     *
     * <pre>
     * 签到天数
     * </pre>
     */
    boolean hasDayNum();
    /**
     * <code>required int32 dayNum = 2;</code>
     *
     * <pre>
     * 签到天数
     * </pre>
     */
    int getDayNum();

    // required int32 goldNum = 3;
    /**
     * <code>required int32 goldNum = 3;</code>
     *
     * <pre>
     * 对应奖励金币
     * </pre>
     */
    boolean hasGoldNum();
    /**
     * <code>required int32 goldNum = 3;</code>
     *
     * <pre>
     * 对应奖励金币
     * </pre>
     */
    int getGoldNum();
  }
  /**
   * Protobuf type {@code com.sy599.game.msg.serverPacket.SevenGoldConfigRes}
   *
   * <pre>
   *七天签到配置信息
   * </pre>
   */
  public static final class SevenGoldConfigRes extends
      com.google.protobuf.GeneratedMessage
      implements SevenGoldConfigResOrBuilder {
    // Use SevenGoldConfigRes.newBuilder() to construct.
    private SevenGoldConfigRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SevenGoldConfigRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SevenGoldConfigRes defaultInstance;
    public static SevenGoldConfigRes getDefaultInstance() {
      return defaultInstance;
    }

    public SevenGoldConfigRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SevenGoldConfigRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dayNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              goldNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.class, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder.class);
    }

    public static com.google.protobuf.Parser<SevenGoldConfigRes> PARSER =
        new com.google.protobuf.AbstractParser<SevenGoldConfigRes>() {
      public SevenGoldConfigRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SevenGoldConfigRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SevenGoldConfigRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required int32 dayNum = 2;
    public static final int DAYNUM_FIELD_NUMBER = 2;
    private int dayNum_;
    /**
     * <code>required int32 dayNum = 2;</code>
     *
     * <pre>
     * 签到天数
     * </pre>
     */
    public boolean hasDayNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 dayNum = 2;</code>
     *
     * <pre>
     * 签到天数
     * </pre>
     */
    public int getDayNum() {
      return dayNum_;
    }

    // required int32 goldNum = 3;
    public static final int GOLDNUM_FIELD_NUMBER = 3;
    private int goldNum_;
    /**
     * <code>required int32 goldNum = 3;</code>
     *
     * <pre>
     * 对应奖励金币
     * </pre>
     */
    public boolean hasGoldNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 goldNum = 3;</code>
     *
     * <pre>
     * 对应奖励金币
     * </pre>
     */
    public int getGoldNum() {
      return goldNum_;
    }

    private void initFields() {
      id_ = 0;
      dayNum_ = 0;
      goldNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDayNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGoldNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, dayNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, goldNum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dayNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, goldNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sy599.game.msg.serverPacket.SevenGoldConfigRes}
     *
     * <pre>
     *七天签到配置信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.class, com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.Builder.class);
      }

      // Construct using com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dayNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        goldNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_descriptor;
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes getDefaultInstanceForType() {
        return com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.getDefaultInstance();
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes build() {
        com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes buildPartial() {
        com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes result = new com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dayNum_ = dayNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.goldNum_ = goldNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes) {
          return mergeFrom((com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes other) {
        if (other == com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDayNum()) {
          setDayNum(other.getDayNum());
        }
        if (other.hasGoldNum()) {
          setGoldNum(other.getGoldNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasDayNum()) {
          
          return false;
        }
        if (!hasGoldNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sy599.game.msg.serverPacket.ConfigMsg.SevenGoldConfigRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required int32 dayNum = 2;
      private int dayNum_ ;
      /**
       * <code>required int32 dayNum = 2;</code>
       *
       * <pre>
       * 签到天数
       * </pre>
       */
      public boolean hasDayNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 dayNum = 2;</code>
       *
       * <pre>
       * 签到天数
       * </pre>
       */
      public int getDayNum() {
        return dayNum_;
      }
      /**
       * <code>required int32 dayNum = 2;</code>
       *
       * <pre>
       * 签到天数
       * </pre>
       */
      public Builder setDayNum(int value) {
        bitField0_ |= 0x00000002;
        dayNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 dayNum = 2;</code>
       *
       * <pre>
       * 签到天数
       * </pre>
       */
      public Builder clearDayNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dayNum_ = 0;
        onChanged();
        return this;
      }

      // required int32 goldNum = 3;
      private int goldNum_ ;
      /**
       * <code>required int32 goldNum = 3;</code>
       *
       * <pre>
       * 对应奖励金币
       * </pre>
       */
      public boolean hasGoldNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 goldNum = 3;</code>
       *
       * <pre>
       * 对应奖励金币
       * </pre>
       */
      public int getGoldNum() {
        return goldNum_;
      }
      /**
       * <code>required int32 goldNum = 3;</code>
       *
       * <pre>
       * 对应奖励金币
       * </pre>
       */
      public Builder setGoldNum(int value) {
        bitField0_ |= 0x00000004;
        goldNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 goldNum = 3;</code>
       *
       * <pre>
       * 对应奖励金币
       * </pre>
       */
      public Builder clearGoldNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        goldNum_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sy599.game.msg.serverPacket.SevenGoldConfigRes)
    }

    static {
      defaultInstance = new SevenGoldConfigRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sy599.game.msg.serverPacket.SevenGoldConfigRes)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025files/ConfigMsg.proto\022\037com.sy599.game." +
      "msg.serverPacket\"\225\001\n\nConfigInfo\022A\n\004sign\030" +
      "\001 \003(\01323.com.sy599.game.msg.serverPacket." +
      "SevenGoldConfigRes\022D\n\013aloneConfig\030\003 \002(\0132" +
      "/.com.sy599.game.msg.serverPacket.AloneC" +
      "onfigRes\"\232\001\n\016AloneConfigRes\022\r\n\005share\030\001 \002" +
      "(\005\022\r\n\005broke\030\002 \002(\005\022\022\n\nbrokeShare\030\003 \002(\005\022\023\n" +
      "\013bingDingNum\030\004 \002(\005\022\023\n\013brokeTigger\030\005 \002(\005\022" +
      "\025\n\rvideoWatchNum\030\006 \002(\005\022\025\n\rvideoAwardNum\030" +
      "\007 \002(\005\"A\n\022SevenGoldConfigRes\022\n\n\002id\030\001 \002(\005\022",
      "\016\n\006dayNum\030\002 \002(\005\022\017\n\007goldNum\030\003 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_ConfigInfo_descriptor,
              new java.lang.String[] { "Sign", "AloneConfig", });
          internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_AloneConfigRes_descriptor,
              new java.lang.String[] { "Share", "Broke", "BrokeShare", "BingDingNum", "BrokeTigger", "VideoWatchNum", "VideoAwardNum", });
          internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sy599_game_msg_serverPacket_SevenGoldConfigRes_descriptor,
              new java.lang.String[] { "Id", "DayNum", "GoldNum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
